<script>
    export const poem = [
        "You try to envelope yourself in",
        "The patterns of objects, and acts, and others.",
        "On a cold night, wrap yourself in a blanket ",
        "you find on the side of the road.",
        "",
        "You are no longer sure if",
        "You want to have never existed.",
        "A cloud that never collapsed.",
        "“What do I do when the",
        "options I have are not enough?”",
        "The stars do not answer.",
        "",
        "Given the time,",
        "you might might stretch out",
        "your hands,",
        "touch every last moon",
        "and stone.",
        "Search breadth without",
        "bias,",
        "one node at a time until lifetimes of sun",
        "were shed like dust from skin in a black,",
        "and endless sky.",
        "",
        "Given the time, you would choose",
        "To go mad searching for a younger earth,",
        "Where he hadn't yet been born,",
        "And there was still time to save him.",
        "",
        "The stars putter and watch their feet",
        "as I burst to know, “Where the fuck is he?”",
        "Contrite, abashed, one gestures to a sign.",
        "“No solicitation.”",
        "",
        "I see them pretending not to stare.",
        "I move slowly so as to not scare them, and breathe:",
        "“Who am I if I don’t want to die anymore?”",
        "Emptied of conviction.",
        "Polyvinyl chloride sewn together",
        "can suspend bodies on air.",
        "They say it lasts forever,",
        "But I am deflated, heavy. A lifetime collapsed",
        "to a single point. I silently",
        "open to gasp for light,",
        "and every time you look away.",
        "",
        "I step out into the night.",
        "",
        "So ours is not an endless sky,",
        "And all I have left are the clothes you wore,",
        "Kissed by the lint you left behind.",
        "",
        "In your lifetime, you will never twice find",
        "The same grain of sand.",
        "And in the span of space,",
        "You will never be rewritten.",
        "",
        "I look at the stars and see he is nowhere and never or weighted again.",
        "He has no more bias.",
        "His body claims no bounds.",
        "But I have begun to consistently see",
        "the same figure at the corners of my vision.",
        "Perhaps you do not need to travel",
        "through forever to find his shape again.",
        "",
        "Perhaps you just need now,",
        "and to let the stars crash in."
    ]
</script>


{#each poem as line}
  {#if (line === '')}
    <br/>
  {/if}
  <p>{line}</p>
{/each}
