export const codeProjects = [
    {
        name: 'ManHunt',
        image: 'images/projects/manhunt.jpg',
        alt: 'ManHunt logo',
        description: 'An AR bounty hunting game where players race each other to capture a "suspect" using their phone cameras and facial recognition ai.',
        techStack: ['TypeScript', 'React', 'Node', 'Socket.IO', 'Tensorflow', '3JS', 'AWS', 'PostgresSQL', 'Sequelize'],
        gitLink: 'https://github.com/Augmented-Lethality/manhunt',
        link: 'https://manhuntar.com/',
    },
    {
        name: 'Delightful Little Treat',
        image: 'images/projects/delightful-little-treat.png',
        alt: 'ManHunt logo',
        description: 'A website where you can press a button to get a delightful little treat delivered to you.',
        techStack: ['TypeScript', 'Svelte', 'AWS', 'Google API', 'Stripe'],
        gitLink: 'https://github.com/kalypsohoman/delightful-little-treat',
        link: 'delightfullittletreat.com',
    },
    {
        name: 'JSF*ck',
        image: 'images/projects/jsf.png',
        alt: 'ManHunt logo',
        description: 'A ongoing project to make a compiler that turns converts regular javascript into JS with just five characters, without losing the functionality of the code.',
        techStack: ['JavaScript'],
        gitLink: '',
        link: undefined,
    },
    {
        name: 'HeadStrong',
        image: 'images/projects/Manhunt.jpeg',
        alt: 'ManHunt logo',
        description: 'HeadStrong is a stress-inducing mindfulness app.',
        techStack: ['JavaScript', 'Node', 'mySQL', 'Sequelize', 'AWS', 'Express', 'Passport and Google auth', 'React', 'Material-UI'],
        gitLink: 'https://github.com/licensed-therapists/headstrong',
        link: undefined,
    },
    {
        name: 'Fellowship Finder',
        image: 'images/projects/Manhunt.jpeg',
        alt: 'ManHunt logo',
        description: 'Fellowship Finder is a web app that allows users to find and meet people with similar interests in games.',
        techStack: ['JavaScript', 'Node', 'mySQL', 'Sequelize', 'AWS', 'Express', 'Passport and Google auth', 'React', 'Material-UI'],
        gitLink: 'https://github.com/party-cubed/fellowship-finder',
        link: undefined,
    }
]