export {default as CloseButton} from "./shared/CloseButton.svelte";
export {default as Contact} from "./about-page/Contact.svelte";
export {default as Email} from "./about-page/emails/Email.svelte"
export {default as NavMenu} from "./shared/NavMenu.svelte";
export {default as Poem} from "./about-page/Poem.svelte";
export {default as PopupContainer} from "./shared/PopupContainer.svelte";
export {default as Project} from "./home-page/Project.svelte";
export {default as SocialMediaLinks} from "./about-page/SocialMediaLinks.svelte";
export { codeProjects } from "./home-page/codeProjects";